---
title: "Analysis"
format:
  html:
    embed-resources: true
editor: visual
execute: 
  echo: false
---

```{r}
#| label: setup
#| include: false

library(tidyverse)
theme_set(theme_light())
library(ggdist)
library(readxl)
library(brms)
```

## Read data

```{r}
#| label: read-data

relatives_ae <- read_xlsx("data/Relatives.xlsx") %>%
  # Remove observations to be excluded
  filter(include == "y") %>%
  mutate(
    manuscript = "Aelfric"
  )

relatives_gdh <- read_xlsx("data/Relatives-2.xlsx", sheet = 3) %>%
  # Remove observations to be excluded
  filter(include == "y") %>%
  mutate(
    manuscript = "GDH"
  )

colnames(relatives_ae) <- c("text", "file", "parallel_set", "parallel_set_id", "dem", "mention", "include", "position", "correlative", "the", "divinity", "generic", "be", "manuscript")

colnames(relatives_gdh) <- c("text", "file", "parallel_set", "parallel_set_id", "dem", "mention", "include", "position", "correlative", "the", "divinity", "generic", "be", "antecedent", "manuscript")

relatives <- bind_rows(relatives_ae, relatives_gdh) %>%
  add_count(manuscript, name = "grand_tot") %>%
  mutate(
    dem = recode_factor(dem, n = "no", se = "SE", that = "THAT"),
    mention = recode_factor(mention, n = "other", y = "second"),
    position = recode_factor(position, n = "other", y = "early"),
    divinity = recode_factor(divinity, n = "other", y = "divinity"),
    mention_position = interaction(mention, position, lex.order = TRUE)
  )

relatives_counts <- relatives %>%
  filter(divinity == "other") %>%
  count(manuscript, dem, mention, position, grand_tot) %>%
  drop_na()
```

Check number of rows and columns

```{r}
#| label: checks

# Number of rows and columns
dim(relatives)
```

Glimpse of the data

```{r}
#| label: relatives
relatives
```

## Plotting

```{r}
#| label: counts

relatives %>%
  drop_na(mention_position, dem) %>%
  ggplot(aes(dem, fill = mention_position)) +
  geom_bar() +
  facet_grid(manuscript ~ divinity) +
  scale_fill_brewer(palette = "PRGn") +
  labs(
    title = "Number of relatives by mention and early/other verb"
  )
```

```{r}
#| label: proportions

relatives %>%
  drop_na(mention_position, dem) %>%
  ggplot(aes(dem, fill = mention_position)) +
  geom_bar(position = "fill") +
  facet_grid(manuscript ~ divinity) +
  scale_fill_brewer(palette = "PRGn") +
  labs(
    title = "Proportion of relatives by mention and early/other verb",
    y = "Proportion"
  )
```

```{r}
#| label: proportions-2

relatives %>%
  drop_na(mention_position, dem) %>%
  ggplot(aes(mention, fill = dem)) +
  geom_bar(position = "fill") +
  facet_grid(manuscript ~ position) +
  scale_fill_brewer(palette = "PRGn") +
  labs(
    title = "Proportion of relatives by mention and early/other verb",
    y = "Proportion"
  )
```

## Modelling

```{r}
#| label: rel-bm

rel_bm <- brm(
  n ~
    dem * mention * position * manuscript +
    offset(log(grand_tot)),
  data = relatives_counts,
  family = poisson,
  backend = "cmdstanr",
  cores = 4,
  threads = threading(4),
  file = "data/rel_bm",
  prior = c(
    prior(normal(4, 1.5), class = Intercept),
    prior(normal(0, 2), class = b)
  ),
  seed = 9899
)
```

I fitted a Bayesian linear model using a Poisson distribution for the outcome variable (number of relatives), with demonstrative, mention and position and manuscript as predictors (including interactions thereof).

```{r}
#| label: rel-bm-conds
#| include: false

conds <- make_conditions(relatives_counts, c("manuscript", "dem")) %>%
  mutate(grand_tot = 100)

conditional_effects(rel_bm, effects = "position:mention", conditions = conds)
```

```{r}
#| label: rel-bm-cond

rel_bm_draws <- as_draws_df(rel_bm)

new_data <- expand_grid(
  dem = c("no", "SE", "THAT"),
  mention = c("other", "second"),
  position = c("other", "early"),
  manuscript = c("Aelfric", "GDH"),
  grand_tot = 100
)

headings <- new_data %>%
  unite("heads", dem:manuscript, sep = ".") %>%
  pull(heads)

rel_bm_cond <- posterior_epred(rel_bm, newdata = new_data)
colnames(rel_bm_cond) <- headings

rel_bm_cond <- as_tibble(rel_bm_cond)

rel_bm_cond_l <- rel_bm_cond %>%
  pivot_longer(everything(), names_to = "condition") %>%
  separate(
    condition,
    c("dem", "mention", "position", "manuscript"),
    sep = "\\."
  ) %>%
  arrange(manuscript, dem, mention, position)
```

```{r rel-bm-cond-ael}
#| label: rel-bm-cond-ael

hilite <- tibble(
  mention = "second", position = "early", dem = "SE",
  xmin = 1.75, xmax = 2.25,
  ymin = 0, ymax = 15
)

rel_bm_cond_l %>%
  filter(manuscript == "Aelfric") %>%
  ggplot(aes(dem, value)) +
  stat_interval(.width = c(0.5, 0.7, 0.9, 0.95), linewidth = 4) +
  facet_grid(position ~ mention, labeller = label_both) +
  coord_cartesian(ylim = c(0, 15)) +
  scale_color_brewer(direction = -1) +
  geom_rect(data = hilite,
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
            fill = NA,
            colour = "#d95f02",
            inherit.aes = FALSE) +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  labs(
    title = "Aelfric manuscript",
    x = "Demonstrative", y = "Percentage"
  )
```

```{r}
#| label: rel-bm-cond-gdh

hilite_2 <- tibble(
  mention = "second", position = "early", dem = "SE",
  xmin = 1.75, xmax = 2.25,
  ymin = 0, ymax = 15
)

rel_bm_cond_l %>%
  filter(manuscript == "GDH") %>%
  ggplot(aes(dem, value)) +
  stat_interval(.width = c(0.5, 0.7, 0.9, 0.95), linewidth = 4) +
  facet_grid(position ~ mention, labeller = label_both) +
  coord_cartesian(ylim = c(0, 15)) +
  scale_color_brewer(direction = -1) +
  geom_rect(data = hilite_2,
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
            fill = NA,
            colour = "#d95f02",
            inherit.aes = FALSE) +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  labs(
    title = "GDH manuscript",
    x = "Demonstrative", y = "Percentage"
  )
```
