---
title: "Analysis 2"
format: html
---

## Read data

```{r}
#| label: setup

#| include: false

library(tidyverse)
theme_set(theme_light())
library(ggdist)
library(readxl)
library(brms)

```

```{r}
#| label: relatives-ehep

relatives_ehep <- read_xlsx("data/Relatives-3.xlsx") %>%
  # Remove observations to be excluded
  filter(include == "y") %>%
  mutate(
    manuscript = "EHEP"
  )

colnames(relatives_ehep) <- c("text", "file", "parallel_set", "parallel_set_id", "dem", "mention", "include", "position", "correlative", "the", "divinity", "generic", "be", "antecedent", "is_called", "extraposed", "verb_only_intervenes", "noun_only_intervenes", "detail", "manuscript")

relatives_ehep <- relatives_ehep %>%
  add_count(manuscript, name = "grand_tot") %>%
  mutate(
    dem = recode_factor(dem, n = "no"),
    mention = recode_factor(mention, n = "other", y = "second"),
    position = recode_factor(position, n = "other", y = "early"),
    divinity = recode_factor(divinity, n = "other", y = "divinity"),
    mention_position = interaction(mention, position, lex.order = TRUE)
  )

relatives_counts <- relatives_ehep %>%
  filter(divinity == "other") %>%
  count(dem, position, grand_tot) %>%
  drop_na()
```

## Modelling

```{r}
#| label: rel-bm

rel_bm_2 <- brm(
  n ~
    dem * position +
    offset(log(grand_tot)),
  data = relatives_counts,
  family = poisson,
  backend = "cmdstanr",
  cores = 4,
  threads = threading(4),
  file = "data/rel_bm_2",
  prior = c(
    prior(normal(4, 1.5), class = Intercept),
    prior(normal(0, 2), class = b)
  ),
  seed = 9899
)
```

```{r}
#| label: rel-bm-2-cond

rel_bm_2_draws <- as_draws_df(rel_bm_2)

new_data_2 <- expand_grid(
  dem = c("no", "se", "that", "thatte"),
  position = c("other", "early"),
  grand_tot = 100
)

headings <- new_data_2 %>%
  unite("heads", dem:position, sep = ".") %>%
  pull(heads)

rel_bm_2_cond <- posterior_epred(rel_bm_2, newdata = new_data_2)
colnames(rel_bm_2_cond) <- headings

rel_bm_2_cond <- as_tibble(rel_bm_2_cond)

rel_bm_2_cond_l <- rel_bm_2_cond %>%
  pivot_longer(everything(), names_to = "condition") %>%
  separate(
    condition,
    c("dem", "position"),
    sep = "\\."
  ) %>%
  arrange(dem, position)
```

```{r}
#| label: rel-bm-2-cond-plot

# hilite <- tibble(
#   mention = "second", position = "early", dem = "SE",
#   xmin = 1.75, xmax = 2.25,
#   ymin = 0, ymax = 15
# )

rel_bm_2_cond_l %>%
  ggplot(aes(dem, value)) +
  stat_interval(.width = c(0.5, 0.7, 0.9, 0.95), linewidth = 4) +
  facet_grid(~ position, labeller = label_both) +
  # coord_cartesian(ylim = c(0, 6)) +
  scale_color_brewer(direction = -1) +
  # geom_rect(data = hilite,
  #           aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
  #           fill = NA,
  #           colour = "#d95f02",
  #           inherit.aes = FALSE) +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  labs(
    title = "EHEP manuscript",
    x = "Demonstrative", y = "Percentage"
  )

ggsave("img/ehep-brm.png", width = 7, height = 5)
```
